on:
  push:
    branches: 
      - pipelinetest
    
jobs:
  test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - if: |
          ${{ 
            github.event_name == 'push' && 
            !contains(join(github.event.commits.*.message), "#skip")
          }} 
        run: echo "no skip"